### ISSUE TITLE
httpcachingproxy option cause error

### ISSUE THREAD

**Issue by elyparker** [geopython/MetaSearch#57]
if i set proxy option in qgis network preferences as <b>httpcachingproxy </b>, the plugin doesn't work and give error:

<pre>
Impossibile caricare il plugin MetaSearch a causa di errore chiamando il metodo initGui()

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISVA~1/apps/qgis/./python\qgis\utils.py", line 213, in startPlugin
    plugins[packageName].initGui()
  File "C:/Documents and Settings/SALVO/.qgis2/python/plugins\MetaSearch\plugin.py", line 106, in initGui
    self.dialog = MetaSearchDialog(self.iface)
  File "C:/Documents and Settings/SALVO/.qgis2/python/plugins\MetaSearch\dialogs\maindialog.py", line 129, in __init__
    self.manageGui()
  File "C:/Documents and Settings/SALVO/.qgis2/python/plugins\MetaSearch\dialogs\maindialog.py", line 158, in manageGui
    self.install_proxy()
  File "C:/Documents and Settings/SALVO/.qgis2/python/plugins\MetaSearch\dialogs\maindialog.py", line 883, in install_proxy
    conn = '%s://%s%s%s' % (ptype, proxy_up, host, proxy_port)
UnboundLocalError: local variable 'ptype' referenced before assignment

Versione Python:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

Versione di QGIS:
2.2.0-Valmiera Valmiera, c3a2817
</pre>

for to work i nee to set proxy option as:

<b>httpProxy</b>

is it possible solve the problem?

**Comment by tomkralidis** [comment]
The proxy stuff happens in https://github.com/geopython/MetaSearch/blob/master/plugin/MetaSearch/dialogs/maindialog.py#L847.

So should this value be `httpProxy` and not `HttpProxy`?

**Comment by elyparker** [comment]
no, the option that give problem is a option of qgis 2.2 <b> HttpCachingProxy</b>
with HttpProxy it doesn't give error
![httpcachingproxy](https://cloud.githubusercontent.com/assets/6742919/3130100/a73c6700-e7f1-11e3-8fb8-bc9adf8df6e8.png)

**Comment by tomkralidis** [comment]
@elyparker thanks.  FYI this was fixed in https://github.com/geopython/MetaSearch/commit/69b9a367a81da7daebd195c0646ff09f87b53391.
